### ISSUE TITLE
Cannot open again and prompt "there is one instance running"

### ISSUE THREAD

**Issue by Blickwinkel1107** [tremwil/SteamP2PInfo#6] opened 2022-04-13 19:04 UTC
Just like the title discribes. Every time I open the application it says there is one instance running already and I don't know why.
![image](https://user-images.githubusercontent.com/31503784/163251974-3759d141-af54-437b-b0fd-71c671e57ba0.png)

**Comment by tremwil** [comment] 2022-04-13 19:07
This can happen if the applocation failed to close properly and is still running in the background. Try to use task manager to forcefully close it before starting it again.

**Comment by Blickwinkel1107** [comment] 2022-04-13 19:13
No problem. But what's the exact process name? I have tried finding it but don't know which it is.
By the way, closing and restarting my PC does not help with the issue.

**Comment by tremwil** [comment] 2022-04-13 19:32
That's definitely weird, it should fix the issue. I'll look into it.

**Comment by tremwil** [comment] 2022-04-19 05:32
Have not been able to figure out the cause for this, if anyone experiences the same issue please share details!

**Comment by Blickwinkel1107** [comment] 2022-04-19 06:14
Update: Currently the program works well and I didn't meet the issue again.

**Comment by tremwil** [comment] 2022-04-19 07:10
Great. Since I wasn't able to replicate it and have not yet received reports of a similar bug, I will assume it was unrelated to the program itself and close this issue.

**Closed by tremwil** 2022-04-19 07:10 UTC
Labels: bug, help wanted
