### ISSUE TITLE
disconnect

### ISSUE THREAD

**Issue by Relinquished001** [tremwil/SteamP2PInfo#3] opened 2022-03-28 20:49 UTC
phantom seems to dc after 2 mins in my world while using

**Comment by tremwil** [comment] 2022-03-29 03:35
This problem is usually caused by EAC not starting up correctly and happened to me a few times without running the tool. I don't see how what I'm doing here could affect EAC as I'm not touching the game process at all. Are you able to reproduce this consistently? To make sure it's caused by the program, testing should be done as follows:

1. Open the game, tool not attached. Summon a player and make sure they can stay in your world for more than two minutes. Repeat a few times to be sure. 
2. Without you or the other player exiting their game, start the program. Summon the player again and see if they get kicked after 2 minutes. Repeat a few times again.

**Comment by Relinquished001** [comment] 2022-03-29 04:54
> 

I checked task manager to make sure eac was running, but will test again tomorrow.

**Comment by tremwil** [comment] 2022-03-29 05:08
I just ran the same test I mentioned previously. Stayed in an online session for a bit more than 5 minutes 3 times in a row with the tool, with one random disconnect. Given that the way EAC heartbeat works in this game in the first place is already unreliable, I really doubt what you experienced was due to my program. Still gonna wait for your own testing before closing this though, it could be some weird system dependent bug.

**Comment by Relinquished001** [comment] 2022-03-29 23:49
Tested again, I had some trouble to begin with the game disconnecting but then after my game crashed and I rebooted the game it didnt disconnect. Made sure eac was running both times so not sure what happened. the overlay definitely seems to be more unstable than using just the program window.

**Comment by tremwil** [comment] 2022-03-30 03:59
>  the overlay definitely seems to be more unstable than using just the program window.

When you open in the game, the overlay is still initialized and running as normal even if disabled. It's simply not visible in that case. Hence that cannot be related to the issues you had. My guess is that your EAC loaded incorrectly the first time. I'm not sure that checking if the process is running is enough to confirm that it was initialized correctly. I'll leave this issue open in the case that it really does affect EAC and people have more reports, but for now a sample size of 1 is simply too small and I don't see any increase in frequency when it comes to disconnects myself.

> Tested again, I had some trouble to begin with the game disconnecting but then after my game crashed and I rebooted the game it didnt disconnect.

As for game crashes, nothing in this program can cause them. It's impossible from a technical standpoint, as the tool does not interact with the game process at all beyond the following:
- Querying the process / window names (basically the same thing as task manager)
- Setting the game window's Z-order when repositioning the overlay after a focus change (this does send an window event to the game, but my program interacts only with Windows here: It's no different from moving the window yourself).

Note that there is an issue where the Steam log file parsing seems to simply stop working for a period of time, hence preventing the detection of peers. If the tool isn't working for you, this is most likely why. I'll open a new issue for that bug since I've received a few reports of it.

**Comment by tremwil** [comment] 2022-04-02 07:52
Considering this fixed given no new reports since the latest version.

**Closed by tremwil** 2022-04-02 07:52 UTC
Labels: bug
